#!/usr/bin/env python3
"""
Convert OTAanimation.jpg sprite sheet into a C header with XBM PROGMEM arrays.
Tailored for monochrome OLED 128x64 screens using U8g2.

Sprite sheet layout:
  - 4 columns x 3 rows = 12 frames
  - 4px border between sprites
  - Target output size: 128 x 64 px (full screen width, keeping aspect ratio)
  
Colors are dithered to 1-bit monochrome so that the ESP32
can push it directly to the display using u8g2.drawXBMP().
"""

import os
from PIL import Image, ImageOps

# Configuration
SPRITE_SHEET = os.path.join(os.path.dirname(__file__), "src", "OTAanimation.png")
OUTPUT_HEADER = os.path.join(os.path.dirname(__file__), "src", "ota_sprites.h")
IMG_DIR = os.path.join(os.path.dirname(__file__), "src", "img")

COLS = 4
ROWS = 3
BORDER = 0

# Target sizes
TARGET_W = 128
TARGET_H = 64

# Boot animation target sizes (scaled down slightly like the original CYD version)
BOOT_W = 80
BOOT_H = 40

# Set to True if you need to invert the source image before dithering to 1-bit
# (Usually OLEDs display white pixels where the image is bright)
INVERT_COLORS = True

def generate_xbm_bytes(img):
    """Converts a 1-bit PIL image to an array of XBM formatted bytes."""
    pixels = img.load()
    w, h = img.size
    bytes_out = []
    for y in range(h):
        for x in range(0, w, 8):
            byte = 0
            for bit in range(8):
                if x + bit < w:
                    # In PIL mode '1', 255 is white.
                    # We want white to be 1 (lit) and black to be 0 (unlit) on OLED.
                    if pixels[x + bit, y] > 127:
                        byte |= (1 << bit)
            bytes_out.append(byte)
    return bytes_out

def main():
    if not os.path.exists(IMG_DIR):
        os.makedirs(IMG_DIR)

    img = Image.open(SPRITE_SHEET).convert("RGB")
    total_w, total_h = img.size
    
    sprite_w = (total_w - (COLS - 1) * BORDER) // COLS
    sprite_h = (total_h - (ROWS - 1) * BORDER) // ROWS
    print(f"Sheet size: {total_w}x{total_h}")
    print(f"Source sprite size: {sprite_w}x{sprite_h}")
    print(f"Target sprite size: {TARGET_W}x{TARGET_H}")
    
    # 1. First pass: extract cells and find their bounding boxes to calculate the global max bounding box
    cells = []
    bboxes = []
    
    for row in range(ROWS):
        for col in range(COLS):
            x = col * (sprite_w + BORDER)
            y = row * (sprite_h + BORDER)
            
            # Extract cell from sheet
            cell = img.crop((x, y, x + sprite_w, y + sprite_h))
            cells.append(cell)
            
            # Convert to grayscale to find bounding box
            cell_gray = cell.convert("L")
            bg_color = cell_gray.getpixel((0, 0))
            if bg_color < 128:
                mask = cell_gray.point(lambda p: 255 if p > 20 else 0, mode="1")
            else:
                mask = cell_gray.point(lambda p: 255 if p < 235 else 0, mode="1")
                
            bbox = mask.getbbox()
            bboxes.append(bbox)
            
    # Find the maximum width and height among all valid bounding boxes
    max_w = max((b[2] - b[0]) for b in bboxes if b)
    max_h = max((b[3] - b[1]) for b in bboxes if b)
    print(f"Detected max sprite bounding box: {max_w}x{max_h}")

    xbm_data_list = []
    
    # 2. Second pass: crop each cell using its bounding box center and the max dimensions
    for idx, (cell, bbox) in enumerate(zip(cells, bboxes)):
        if bbox:
            cx = (bbox[0] + bbox[2]) / 2
            cy = (bbox[1] + bbox[3]) / 2
            
            crop_x0 = int(cx - max_w / 2)
            crop_y0 = int(cy - max_h / 2)
            crop_x1 = int(cx + max_w / 2)
            crop_y1 = int(cy + max_h / 2)
            
            # Crop exactly the stabilized subregion
            sprite = cell.crop((crop_x0, crop_y0, crop_x1, crop_y1))
        else:
            # Fallback if no bright pixels
            sprite = cell
            
        # Scale down to target size
        sprite = sprite.resize((TARGET_W, TARGET_H), Image.LANCZOS)
            
        sprite = sprite.convert("L")
        if INVERT_COLORS:
            sprite = ImageOps.invert(sprite)
        
        # Convert to 1-bit monochrome (dithered)
        sprite_bw = sprite.convert("1")
            
        # Save to PNG in img/ folder
        out_path = os.path.join(IMG_DIR, f"frame_{idx:02d}.png")
        sprite_bw.save(out_path, format="PNG")
        
        # Generate XBM bytes
        xbm_bytes = generate_xbm_bytes(sprite_bw)
        xbm_data_list.append(xbm_bytes)
        
        print(f"  Frame {idx}: saved to {out_path} ({len(xbm_bytes)} bytes)")
    
    # Write C header
    with open(OUTPUT_HEADER, "w") as f:
        f.write("// Auto-generated by convert_sprites.py — DO NOT EDIT\n")
        f.write("// Source: OTAanimation.jpg (4x3 grid, 12 frames)\n")
        f.write("#pragma once\n")
        f.write("#include <pgmspace.h>\n\n")
        f.write(f"#define OTA_SPRITE_W {TARGET_W}\n")
        f.write(f"#define OTA_SPRITE_H {TARGET_H}\n")
        f.write(f"#define OTA_SPRITE_COUNT {COLS * ROWS}\n\n")
        
        total_size = 0
        for i, data in enumerate(xbm_data_list):
            total_size += len(data)
            f.write(f"const uint8_t ota_sprite_{i}[] PROGMEM = {{\n")
            for j in range(0, len(data), 16):
                line = ", ".join(f"0x{b:02X}" for b in data[j:j+16])
                f.write(f"  {line},\n")
            f.write("};\n\n")
        
        # Pointer arrays for indexed access
        f.write("const uint8_t* const ota_sprites[OTA_SPRITE_COUNT] PROGMEM = {\n")
        for i in range(COLS * ROWS):
            f.write(f"  ota_sprite_{i},\n")
        f.write("};\n\n")
        
        # Add special boot sprites for frames 4, 8, 11 (scaled to BOOT_W x BOOT_H)
        boot_frames = [4, 8, 11]
        f.write(f"// Special boot sprites (scaled to {BOOT_W}x{BOOT_H})\n")
        f.write(f"#define BOOT_SPRITE_W {BOOT_W}\n")
        f.write(f"#define BOOT_SPRITE_H {BOOT_H}\n\n")
        
        for i, f_idx in enumerate(boot_frames):
            cell = cells[f_idx]
            bbox = bboxes[f_idx]
            
            if bbox:
                cx = (bbox[0] + bbox[2]) / 2
                cy = (bbox[1] + bbox[3]) / 2
                crop_x0 = int(cx - max_w / 2)
                crop_y0 = int(cy - max_h / 2)
                crop_x1 = int(cx + max_w / 2)
                crop_y1 = int(cy + max_h / 2)
                boot_sprite = cell.crop((crop_x0, crop_y0, crop_x1, crop_y1))
            else:
                boot_sprite = cell

            boot_sprite = boot_sprite.resize((BOOT_W, BOOT_H), Image.LANCZOS)
            
            boot_sprite = boot_sprite.convert("L")
            if INVERT_COLORS:
                boot_sprite = ImageOps.invert(boot_sprite)
            
            boot_sprite_bw = boot_sprite.convert("1")
            
            boot_path = os.path.join(IMG_DIR, f"boot_{i}.png")
            boot_sprite_bw.save(boot_path, format="PNG")
            
            boot_bytes = generate_xbm_bytes(boot_sprite_bw)
            total_size += len(boot_bytes)
            
            f.write(f"// Special boot sprite {i} (frame {f_idx}, {BOOT_W}x{BOOT_H})\n")
            f.write(f"const uint8_t ota_sprite_boot_{i}[] PROGMEM = {{\n")
            for j in range(0, len(boot_bytes), 16):
                line = ", ".join(f"0x{b:02X}" for b in boot_bytes[j:j+16])
                f.write(f"  {line},\n")
            f.write("};\n\n")
    
    print(f"\nGenerated {OUTPUT_HEADER}")
    print(f"Total XBM binary data: {total_size:,} bytes ({total_size / 1024:.2f} KB)")

if __name__ == "__main__":
    main()
